### ISSUE TITLE
Rename io.arkitik.radix.develop.shared.error.Error to RadixError to avoid conflict with Kotlin.Error class

### ISSUE THREAD

**Issue by MousaHalaseh** [arkitik/radix#4]
In more than one project we've been aliasing the import as below:

`import io.arkitik.radix.develop.shared.error.Error as RadixError
`

I suggest we refactor the class name to eliminate any ambiguity.

@ibm-iloom let me know if I can proceed with a PR to resolve this.

**Comment by ibm-iloom** [comment]
@MousaHalaseh Yes, for sure, but keep in mind that multiple projects already release, so; better to keep the class with the same name but define a `typealias` using the suggested name and mark the original Error class as deprecated.

**Comment by MousaHalaseh** [comment]
@ibm-iloom I think creating a separate `RadixError` class altogehter is a better approach so that new projects use the new type directly instead of relying on a `typealias`, plus the fact that we can't reference the new `typealias` in the `Deprecated` annotation since it would techncially still reference a deprecated type (itself).

I have opened a PR to address this #5
